In [8]:
import numpy as np
import pandas as pd

In [11]:
a=pd.read_csv(r"C:\Users\Bibhu\Downloads\amazon+product+and+google+locations+reviews\y_amazon-google-large.csv")
a

         Unnamed: 0                   ds     y  unique_id
0                 0  2020-01-01 08:00:00   6.0          0
1                 1  2020-01-01 09:00:00   0.0          0
2                 2  2020-01-01 10:00:00   4.0          0
3                 3  2020-01-01 11:00:00   8.0          0
4                 4  2020-01-01 12:00:00   4.0          0
...             ...                  ...   ...        ...
3054995     7826773  2021-06-25 19:00:00   6.0        238
3054996     7826774  2021-06-25 20:00:00  21.0        238
3054997     7826775  2021-06-25 21:00:00  11.0        238
3054998     7826776  2021-06-25 22:00:00  11.0        238
3054999     7826777  2021-06-25 23:00:00   7.0        238

[3055000 rows x 4 columns]

In [13]:
a.columns=['unnamed','ds','y','unique_id']
a

         unnamed                   ds     y  unique_id
0              0  2020-01-01 08:00:00   6.0          0
1              1  2020-01-01 09:00:00   0.0          0
2              2  2020-01-01 10:00:00   4.0          0
3              3  2020-01-01 11:00:00   8.0          0
4              4  2020-01-01 12:00:00   4.0          0
...          ...                  ...   ...        ...
3054995  7826773  2021-06-25 19:00:00   6.0        238
3054996  7826774  2021-06-25 20:00:00  21.0        238
3054997  7826775  2021-06-25 21:00:00  11.0        238
3054998  7826776  2021-06-25 22:00:00  11.0        238
3054999  7826777  2021-06-25 23:00:00   7.0        238

[3055000 rows x 4 columns]

In [14]:
a.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3055000 entries, 0 to 3054999
Data columns (total 4 columns):
 #   Column     Dtype
---  ------     -----
 0   unnamed    int64
 1   ds         object
 2   y          float64
 3   unique_id  int64
dtypes: float64(1), int64(2), object(1)
memory usage: 93.2+ MB

In [15]:
a.isnull().sum()

unnamed      0
ds           0
y            0
unique_id    0
dtype: int64

In [17]:
a.shape

(3055000, 4)

In [18]:
a.size

12220000

In [19]:
for i in a.columns:
    print(i,":","\n",a[i].unique())

unnamed :
 [      0       1       2 ... 7826775 7826776 7826777]
ds :
 ['2020-01-01 08:00:00' '2020-01-01 09:00:00' '2020-01-01 10:00:00' ...
 '2021-06-25 21:00:00' '2021-06-25 22:00:00' '2021-06-25 23:00:00']
y :
 [6.000e+00 0.000e+00 4.000e+00 ... 4.114e+03 4.070e+03 2.928e+03]
unique_id :
 [  0   1   2   3   4   5   6   7   8   9  10  12  14  15  16  17  18  19
  20  22  23  24  25  26  27  28  30  31  32  33  34  35  36  37  38  39
  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54  55  56  57
  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72  73  74  75
  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90  91  92  93
  94  95  96  97  98  99 100 101 102 103 104 105 106 107 108 109 110 111
 112 113 114 115 116 117 118 119 120 121 122 123 124 125 126 127 128 129
 130 131 132 133 134 135 136 137 138 139 140 141 142 143 144 145 146 147
 148 149 150 151 152 153 154 155 156 157 158 159 160 161 162 163 164 165
 166 167 168 169 170 171 172 173 174 175 176 177 178 179 180 181 182 183
 184 185 186 187 188 189 190 191 192 193 194 195 196 197 198 199 200 201
 202 203 204 205 206 207 208 209 210 211 212 213 214 215 216 217 218 219
 220 221 222 223 224 225 226 227 228 229 230 231 232 233 234 235 236 237
 238]

In [25]:
for i in a.columns:
    print(i, ":", "\n", a[i].unique())

unnamed :
 [      0       1       2 ... 7826775 7826776 7826777]
ds :
 ['2020-01-01 08:00:00' '2020-01-01 09:00:00' '2020-01-01 10:00:00' ...
 '2021-06-25 21:00:00' '2021-06-25 22:00:00' '2021-06-25 23:00:00']
y :
 [6.000e+00 0.000e+00 4.000e+00 ... 4.114e+03 4.070e+03 2.928e+03]
unique_id :
 [  0   1   2   3   4   5   6   7   8   9  10  12  14  15  16  17  18  19
  20  22  23  24  25  26  27  28  30  31  32  33  34  35  36  37  38  39
  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54  55  56  57
  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72  73  74  75
  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90  91  92  93
  94  95  96  97  98  99 100 101 102 103 104 105 106 107 108 109 110 111
 112 113 114 115 116 117 118 119 120 121 122 123 124 125 126 127 128 129
 130 131 132 133 134 135 136 137 138 139 140 141 142 143 144 145 146 147
 148 149 150 151 152 153 154 155 156 157 158 159 160 161 162 163 164 165
 166 167 168 169 170 171 172 173 174 175 176 177 178 179 180 181 182 183
 184 185 186 187 188 189 190 191 192 193 194 195 196 197 198 199 200 201
 202 203 204 205 206 207 208 209 210 211 212 213 214 215 216 217 218 219
 220 221 222 223 224 225 226 227 228 229 230 231 232 233 234 235 236 237
 238]

In [28]:
a.describe()

            unnamed             y     unique_id
count  3.055000e+06  3.055000e+06  3.055000e+06
mean   3.969550e+06  1.871836e+02  1.207106e+02
std    2.242462e+06  3.553579e+02  6.830310e+01
min    0.000000e+00  0.000000e+00  0.000000e+00
25%    2.045272e+06  2.600000e+01  6.200000e+01
50%    3.979050e+06  7.900000e+01  1.210000e+02
75%    5.912829e+06  1.950000e+02  1.800000e+02
max    7.826777e+06  1.952300e+04  2.380000e+02