In [1]:
import numpy as np

In [2]:
import pandas as pd

In [32]:
import pandas as pd

df1 = pd.DataFrame({
    'Days': [2, 3, 4, 5, 6],
    'places': ['puri', 'Manali', 'Goa', 'puri', 'Bali'],
    'Visitora': [5500, 5000, 4890, 2500, 3400],
    'mode': ['bus', 'train', 'Bus', 'Bike', 'cycle']
})

df1

   Days  places  Visitora   mode
0     2    puri      5500    bus
1     3  Manali      5000  train
2     4     Goa      4890    Bus
3     5    puri      2500   Bike
4     6    Bali      3400  cycle

In [7]:
np.shape(df1)

(5, 4)

In [8]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Days      5 non-null      int64
 1   places    5 non-null      object
 2   Visitora  5 non-null      int64
 3   mode      5 non-null      object
dtypes: int64(2), object(2)
memory usage: 292.0+ bytes

In [11]:
#  it check the null value
df1.isnull()

    Days  places  Visitora   mode
0  False   False     False  False
1  False   False     False  False
2  False   False     False  False
3  False   False     False  False
4  False   False     False  False

In [19]:
df1.isnull().sum()

Days        0
places      0
Visitora    0
mode        0
dtype: int64

In [26]:
df1.dtypes

Days         int64
places      object
Visitora     int64
mode        object
dtype: object

In [33]:
# unique
df1.places.unique()

array(['puri', 'Manali', 'Goa', 'Bali'], dtype=object)

In [34]:
df1.Visitora.max()

5500

In [35]:
df1.Visitora.mean()

4258.0

In [36]:
# work on integer 
df1.describe()

           Days     Visitora
count  5.000000     5.000000
mean   4.000000  4258.000000
std    1.581139  1256.908907
min    2.000000  2500.000000
25%    3.000000  3400.000000
50%    4.000000  4890.000000
75%    5.000000  5000.000000
max    6.000000  5500.000000

In [39]:
df1.describe(include=object)

       places mode
count       5    5
unique      4    5
top      puri  bus
freq        2    1

In [37]:
df1.describe(include='all')

            Days places     Visitora mode
count   5.000000      5     5.000000    5
unique       NaN      4          NaN    5
top          NaN   puri          NaN  bus
freq         NaN      2          NaN    1
mean    4.000000    NaN  4258.000000  NaN
std     1.581139    NaN  1256.908907  NaN
min     2.000000    NaN  2500.000000  NaN
25%     3.000000    NaN  3400.000000  NaN
50%     4.000000    NaN  4890.000000  NaN
75%     5.000000    NaN  5000.000000  NaN
max     6.000000    NaN  5500.000000  NaN

In [41]:
# show object only
df1.describe(include='O')

       places mode
count       5    5
unique      4    5
top      puri  bus
freq        2    1

# To replace all null

In [59]:
import pandas as pd

df2 = pd.DataFrame({
    'Days': [2, np.nan, 4, 5, 6],
    'places': ['puri', 'Manali', 'Goa', 'puri', np.nan],
    'Visitora': [5500, 5000, 4890, 2500, 3400],
    'mode': ['bus', 'train', 'Bus', 'Bike', 'cycle']
})

df2

   Days  places  Visitora   mode
0   2.0    puri      5500    bus
1   NaN  Manali      5000  train
2   4.0     Goa      4890    Bus
3   5.0    puri      2500   Bike
4   6.0     NaN      3400  cycle

In [46]:
df2.shape

(5, 4)

In [47]:
df2.info

<bound method DataFrame.info of    Days  places  Visitora   mode
0   2.0    puri      5500    bus
1   NaN  Manali      5000  train
2   4.0     Goa      4890    Bus
3   5.0    puri      2500   Bike
4   6.0     NaN      3400  cycle>

In [48]:
df2.describe

<bound method NDFrame.describe of    Days  places  Visitora   mode
0   2.0    puri      5500    bus
1   NaN  Manali      5000  train
2   4.0     Goa      4890    Bus
3   5.0    puri      2500   Bike
4   6.0     NaN      3400  cycle>

In [49]:
df2.isnull()

    Days  places  Visitora   mode
0  False   False     False  False
1   True   False     False  False
2  False   False     False  False
3  False   False     False  False
4  False    True     False  False

In [50]:
df2.isnull().sum()

Days        1
places      1
Visitora    0
mode        0
dtype: int64

In [61]:
df2.dtypes

Days        float64
places       object
Visitora      int64
mode         object
dtype: object

In [51]:
df2.places.unique()

array(['puri', 'Manali', 'Goa', nan], dtype=object)

In [52]:
df2.Visitora.max()

5500

In [53]:
df2.Visitora.mean()

4258.0

In [54]:
df2.describe()

           Days     Visitora
count  4.000000     5.000000
mean   4.250000  4258.000000
std    1.707825  1256.908907
min    2.000000  2500.000000
25%    3.500000  3400.000000
50%    4.500000  4890.000000
75%    5.250000  5000.000000
max    6.000000  5500.000000

In [71]:
# fillna -> use to replace the null value
# in case of numeric column we replace 'nan' with nan/average.
df2.Days = df2.Days.fillna(8.25)
df2.describe()

           Days     Visitora
count  5.000000     5.000000
mean   5.050000  4258.000000
std    2.321099  1256.908907
min    2.000000  2500.000000
25%    4.000000  3400.000000
50%    5.000000  4890.000000
75%    6.000000  5000.000000
max    8.250000  5500.000000

In [78]:
# in place of object we replace the 'nan'with top
df2.places=df2.places.fillna('puri')
df2

   Days  places  Visitora   mode
0  2.00    puri      5500    bus
1  8.25  Manali      5000  train
2  4.00     Goa      4890    Bus
3  5.00     Goa      2500   Bike
4  6.00    puri      3400  cycle

In [80]:
df2.isnull().sum()

Days        0
places      0
Visitora    0
mode        0
dtype: int64

In [62]:
df2.describe(include='all')

            Days places     Visitora mode
count   4.000000      4     5.000000    5
unique       NaN      3          NaN    5
top          NaN   puri          NaN  bus
freq         NaN      2          NaN    1
mean    4.250000    NaN  4258.000000  NaN
std     1.707825    NaN  1256.908907  NaN
min     2.000000    NaN  2500.000000  NaN
25%     3.500000    NaN  3400.000000  NaN
50%     4.500000    NaN  4890.000000  NaN
75%     5.250000    NaN  5000.000000  NaN
max     6.000000    NaN  5500.000000  NaN

In [87]:
import pandas as pd

df3 = pd.DataFrame({
    'Days': [2, 5, 4, 5, 6],
    'places': ['puri', 'Manali', 'Goa', 'puri', "?"],
    'Visitora': [5500, 5000, 4890, "?", 3400],
    'mode': ['bus', 'train', 'Bus', 'Bike', 'cycle']
})

df3

   Days  places Visitora   mode
0     2    puri     5500    bus
1     5  Manali     5000  train
2     4     Goa     4890    Bus
3     5    puri        ?   Bike
4     6       ?     3400  cycle

In [137]:
df3.isnull().sum()

Days        0
places      0
Visitora    0
mode        0
dtype: int64

In [91]:
df3.shape

(5, 4)

In [88]:
df3.info

<bound method DataFrame.info of    Days  places Visitora   mode
0     2    puri     5500    bus
1     5  Manali     5000  train
2     4     Goa     4890    Bus
3     5    puri        ?   Bike
4     6       ?     3400  cycle>

In [90]:
df3.isnull()

    Days  places  Visitora   mode
0  False   False     False  False
1  False   False     False  False
2  False   False     False  False
3  False   False     False  False
4  False   False     False  False

In [92]:
df3.isnull().sum()

Days        0
places      0
Visitora    0
mode        0
dtype: int64

In [95]:
df3.dtypes

Days         int64
places      object
Visitora    object
mode        object
dtype: object

In [96]:
df3.Visitora.unique()

array([5500, 5000, 4890, '?', 3400], dtype=object)

In [97]:
df3.places.unique()

array(['puri', 'Manali', 'Goa', '?'], dtype=object)

In [101]:
df3.describe()

           Days
count  5.000000
mean   4.400000
std    1.516575
min    2.000000
25%    4.000000
50%    5.000000
75%    5.000000
max    6.000000

In [110]:
df3.Visitora = df3.Visitora.fillna(9.25)
df3

   Days  places Visitora   mode
0     2    puri     5500    bus
1     5  Manali     5000  train
2     4     Goa     4890    Bus
3     5     Goa        ?   Bike
4     6       ?     3400  cycle

In [105]:
df3.places=df3.places.fillna('puri')
df3.describe(include='all')

            Days places  Visitora mode
count   5.000000      5       5.0    5
unique       NaN      4       5.0    5
top          NaN    Goa    5500.0  bus
freq         NaN      2       1.0    1
mean    4.400000    NaN       NaN  NaN
std     1.516575    NaN       NaN  NaN
min     2.000000    NaN       NaN  NaN
25%     4.000000    NaN       NaN  NaN
50%     5.000000    NaN       NaN  NaN
75%     5.000000    NaN       NaN  NaN
max     6.000000    NaN       NaN  NaN

In [104]:
df3.info

<bound method DataFrame.info of    Days  places Visitora   mode
0     2    puri     5500    bus
1     5  Manali     5000  train
2     4     Goa     4890    Bus
3     5     Goa        ?   Bike
4     6       ?     3400  cycle>

In [120]:
df3.places=df3.places.replace('?','puri')

In [121]:
df3

   Days  places Visitora   mode
0     2    puri     5500    bus
1     5  Manali     5000  train
2     4     Goa     4890    Bus
3     5    puri        ?   Bike
4     6    puri     3400  cycle

In [130]:
df3.Visitora=df3.Visitora.replace('?',np.nan)

In [134]:
df3.Visitora.dtypes

dtype('float64')

In [131]:
df3.Visitora.mean()

3759.71

In [132]:
df3.Visitora=df3.Visitora.fillna(4867.56)

In [133]:
df3.describe

<bound method NDFrame.describe of    Days  places  Visitora   mode
0     2    puri   5500.00    bus
1     5  Manali   5000.00  train
2     4     Goa   4890.00    Bus
3     5    puri      8.55   Bike
4     6       ?   3400.00  cycle>

In [135]:
df3.isnull().sum()

Days        0
places      0
Visitora    0
mode        0
dtype: int64