# pandas

In [ ]:
# pandas: pandas is a python library use to store , organise ,analysis & maipulate data in table like format.
# we can read and create datasets using pandas.

In [ ]:
# pandas are two types:
# 1.Series(single columns & multiple rows)
# 2.Dataframe(multiple columns & rows)

In [7]:
import pandas as pd

In [5]:
# to check the version of pandas 
pd.__version__

'2.2.2'

In [6]:
# Series:
s=pd.Series(['a','b','c','d'])
s

0    a
1    b
2    c
3    d
dtype: object

In [4]:
type(s)

pandas.core.series.Series

In [11]:
# Assing index position 
s=pd.Series(['a','b','c','d'],index=[10,20,30,40])
s

10    a
20    b
30    c
40    d
dtype: object

In [12]:
type(s)

pandas.core.series.Series

In [16]:
# indexing
s[30]

'c'

In [19]:
# Assigning same index number multiple time
s=pd.Series(['a','b','c','d','e'],index=[10,20,20,40,50])
s

10    a
20    b
20    c
40    d
50    e
dtype: object

In [20]:
# slicing
s[1:5:1]

20    b
20    c
40    d
50    e
dtype: object

In [21]:
s[20:50:1]

Series([], dtype: object)

In [38]:
# .loc->loc at the INDEX .jadi index change kariba au slicing karibaku loc use kara.
s=pd.Series(['a','b','c','d','e'],index=[10,20,20,40,50])
print(s)
s.loc[20:50:1]

10    a
20    b
20    c
40    d
50    e
dtype: object

20    b
20    c
40    d
50    e
dtype: object

In [33]:
# Tuple to series
t=pd.Series((10,20,30,40))
t
t[3]

40

In [34]:
t[-3] # series re tuple use kale indexing haba nahi

KeyError: -3

In [39]:
# for -ve indexing we can use ilok:
t.iloc[-1]

40

In [41]:
# List to series
l=pd.Series([10,20,30,40])
l

0    10
1    20
2    30
3    40
dtype: int64

In [43]:
# set to series
l=pd.Series(10,20,30,40)
l

TypeError: Index(...) must be called with a collection of some kind, 20 was passed

In [44]:
# Dictionary to series
d=pd.Series({'a':1,'b':2,'c':3,'d':4})
d

a    1
b    2
c    3
d    4
dtype: int64

In [45]:
d=pd.Series({'a':1,'b':2,'c':3,'d':4},index={'e','b','f','d'})
d

f    NaN
e    NaN
b    2.0
d    4.0
dtype: float64

In [46]:
# indexing
d['b']

2.0

In [52]:
d[0:2:1]

f   NaN
e   NaN
dtype: float64

In [8]:
# DataFrame: multiple roes & multiple columns
d={'name':['ram','sita','hari','subha','Bhagya'],
  'Roll':[21,22,23,24,25],
  'skills': ['cooking','Travel','sleeping','study','Foodie']}
df=pd.DataFrame(d)
df

     name  Roll    skills
0     ram    21   cooking
1    sita    22    Travel
2    hari    23  sleeping
3   subha    24     study
4  Bhagya    25    Foodie

In [9]:
# indexing 
df.name[1]

'sita'

In [10]:
df.Roll[1]

22

In [11]:
df[0:3:1]

   name  Roll    skills
0   ram    21   cooking
1  sita    22    Travel
2  hari    23  sleeping

In [12]:
df.loc[0]

name          ram
Roll           21
skills    cooking
Name: 0, dtype: object

In [80]:
# iloc (integer location)-> use the slicing on a DataFrame
# iloc[row,column]
df.iloc[3::]

     name  Roll  skills
3   subha    24   study
4  Bhagya    25  Foodie

In [81]:
df.iloc[::,2]

0     cooking
1      Travel
2    sleeping
3       study
4      Foodie
Name: skills, dtype: object

In [82]:
df.iloc[::2,::]

     name  Roll    skills
0     ram    21   cooking
2    hari    23  sleeping
4  Bhagya    25    Foodie

In [83]:
df.iloc[::-1,::-1]

     skills  Roll    name
4    Foodie    25  Bhagya
3     study    24   subha
2  sleeping    23    hari
1    Travel    22    sita
0   cooking    21     ram

In [85]:
# head(): it represent top rows (by default 5) but you can change it by putting some number in () 

df.head(5)

     name  Roll    skills
0     ram    21   cooking
1    sita    22    Travel
2    hari    23  sleeping
3   subha    24     study
4  Bhagya    25    Foodie

In [86]:
df.head(3)

   name  Roll    skills
0   ram    21   cooking
1  sita    22    Travel
2  hari    23  sleeping

In [91]:
# tail(): show from buttom..
df.tail(3)

     name  Roll    skills
2    hari    23  sleeping
3   subha    24     study
4  Bhagya    25    Foodie

In [13]:
# sample: represent random row /sample (by default one)
df.sample()

    name  Roll skills
3  subha    24  study

In [14]:
df.sample(3)

     name  Roll   skills
0     ram    21  cooking
4  Bhagya    25   Foodie
3   subha    24    study

In [15]:
df=df.rename(columns={'Roll':'Roll_number'})
df

     name  Roll_number    skills
0     ram           21   cooking
1    sita           22    Travel
2    hari           23  sleeping
3   subha           24     study
4  Bhagya           25    Foodie

In [16]:
df=df.rename(columns={'name':'students_name'})
df

  students_name  Roll_number    skills
0           ram           21   cooking
1          sita           22    Travel
2          hari           23  sleeping
3         subha           24     study
4        Bhagya           25    Foodie

In [17]:
df=df.rename(columns={'skills':'students_skills'})
df

  students_name  Roll_number students_skills
0           ram           21         cooking
1          sita           22          Travel
2          hari           23        sleeping
3         subha           24           study
4        Bhagya           25          Foodie

In [18]:
# set_index():
df.set_index('Roll_number',inplace=True)
df

            students_name students_skills
Roll_number
21                    ram         cooking
22                   sita          Travel
23                   hari        sleeping
24                  subha           study
25                 Bhagya          Foodie

In [2]:
df=df.set_index('Roll_number',inplace=True)
df

NameError: name 'df' is not defined

In [19]:
df.reset_index()
df

            students_name students_skills
Roll_number
21                    ram         cooking
22                   sita          Travel
23                   hari        sleeping
24                  subha           study
25                 Bhagya          Foodie

In [15]:
import pandas as pd

df1 = pd.DataFrame({
    'Days': [2, 3, 4, 5, 6],
    'places': ['puri', 'Manali', 'Goa', 'puri', 'Bali'],
    'Visitora': [5500, 5000, 4890, 2500, 3400],
    'mode': ['bus', 'train', 'Bus', 'Bike', 'cycle']
})

df1

   Days  places  Visitora   mode
0     2    puri      5500    bus
1     3  Manali      5000  train
2     4     Goa      4890    Bus
3     5    puri      2500   Bike
4     6    Bali      3400  cycle